server:
  port: 8080

spring:
  application:
    name: cdr-reporter

  datasource:
    url: jdbc:postgresql://cdr_postgres_main:5432/cdr_db
    username: postgres
    password: postgres

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    root: INFO
    com.Argela.aop: DEBUG
    com.Argela.controller: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui/index.html
